WebApp/Controllers/StorageTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Data;
using WebApp.Infrastructure;
using WebApp.Models;
using WebApp.Models.SortStates;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class StorageTypesController : Controller
    {
        private readonly RecPointContext _context;
        private int _pageSize = 20;
        private string _currentPage = "pageStorageTypes";
        private string _currentSortOrder = "sortOrderStorageTypes";
        private string _currentFilterStorageType = "searchStorageTypeStorageTypes";

        public StorageTypesController(RecPointContext context)
        {
            _context = context;
        }

        // GET: StorageTypes

        [ResponseCache(Location = ResponseCacheLocation.Any, Duration = 294)]
        public IActionResult Index(SortStateStorageType? sortOrder, string searchStorageType, int? page, bool resetFilter = false)
        {
            IQueryable<StorageType> storageTypes = _context.StorageTypes;
            sortOrder ??= GetSortStateFromSessionOrSetDefault();
            page ??= GetCurrentPageFromSessionOrSetDefault();
            if (resetFilter)
            {
                HttpContext.Session.Remove(_currentFilterStorageType);
            }
            searchStorageType ??= GetCurrentFilterStorageTypeOrSetDefault();
            storageTypes = Search(storageTypes, (SortStateStorageType)sortOrder, searchStorageType);
            var count = storageTypes.Count();
            PageViewModel pageViewModel = new PageViewModel(count, (int)page, _pageSize);
            storageTypes = storageTypes.Skip(((int)pageViewModel.PageNumber - 1) * _pageSize).Take(_pageSize);
            SaveValuesInSession((SortStateStorageType)sortOrder, (int)page, searchStorageType);
            IndexViewModel<StorageType> StorageTypesView = new IndexViewModel<StorageType>()
            {
                Items = storageTypes,
                PageViewModel = pageViewModel
            };
            return View(StorageTypesView);
        }

        // GET: StorageTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.StorageTypes == null)
            {
                return NotFound();
            }

            var storageType = await _context.StorageTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (storageType == null)
            {
                return NotFound();
            }

            return View(storageType);
        }

        // GET: StorageTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: StorageTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Temperature,Humidity,Requirement,Equipment")] StorageType storageType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(storageType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(storageType);
        }

        // GET: StorageTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.StorageTypes == null)
            {
                return NotFound();
            }

            var storageType = await _context.StorageTypes.FindAsync(id);
            if (storageType == null)
            {
                return NotFound();
            }
            return View(storageType);
        }

        // POST: StorageTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Temperature,Humidity,Requirement,Equipment")] StorageType storageType)
        {
            if (id != storageType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(storageType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StorageTypeExists(storageType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(storageType);
        }

        // GET: StorageTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.StorageTypes == null)
            {
                return NotFound();
            }

            var storageType = await _context.StorageTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (storageType == null)
            {
                return NotFound();
            }

            return View(storageType);
        }

        // POST: StorageTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.StorageTypes == null)
            {
                return Problem("Entity set 'RecPointContext.StorageTypes'  is null.");
            }
            var storageType = await _context.StorageTypes.FindAsync(id);
            if (storageType != null)
            {
                _context.StorageTypes.Remove(storageType);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StorageTypeExists(int id)
        {
          return _context.StorageTypes.Any(e => e.Id == id);
        }
        private IQueryable<StorageType> Search(IQueryable<StorageType> storageTypes,
            SortStateStorageType sortOrder, string searchStorageType)
        {
            ViewData["searchStorageType"] = searchStorageType;
            storageTypes = storageTypes.Where(p => p.Name.Contains(searchStorageType ?? ""));

            ViewData["Name"] = sortOrder == SortStateStorageType.NameAsc ? SortStateStorageType.NameDesc : SortStateStorageType.NameAsc;
            ViewData["Temperature"] = sortOrder == SortStateStorageType.TemperatureAsc ? SortStateStorageType.TemperatureDesc : SortStateStorageType.TemperatureAsc;
            ViewData["Humidity"] = sortOrder == SortStateStorageType.HumidityAsc ? SortStateStorageType.HumidityDesc : SortStateStorageType.HumidityAsc;

            storageTypes = sortOrder switch
            {
                SortStateStorageType.NameAsc => storageTypes.OrderBy(st => st.Name),
                SortStateStorageType.NameDesc => storageTypes.OrderByDescending(st => st.Name),
                SortStateStorageType.HumidityAsc => storageTypes.OrderBy(st => st.Humidity),
                SortStateStorageType.HumidityDesc => storageTypes.OrderByDescending(st => st.Humidity),
                SortStateStorageType.TemperatureAsc => storageTypes.OrderBy(st => st.Temperature),
                SortStateStorageType.TemperatureDesc => storageTypes.OrderByDescending(st => st.Temperature),
                SortStateStorageType.No => storageTypes.OrderBy(st => st.Id),
                _ => storageTypes.OrderBy(st => st.Id)
            };

            return storageTypes;
        }
        private void SaveValuesInSession(SortStateStorageType sortOrder, int page, string searchStorageType)
        {
            HttpContext.Session.Remove(_currentSortOrder);
            HttpContext.Session.Remove(_currentPage);
            HttpContext.Session.Remove(_currentFilterStorageType);
            HttpContext.Session.Set(_currentSortOrder, sortOrder);
            HttpContext.Session.SetString(_currentPage, page.ToString());
            HttpContext.Session.SetString(_currentFilterStorageType, searchStorageType);
        }
        private SortStateStorageType GetSortStateFromSessionOrSetDefault()
        {
            return HttpContext.Session.Keys.Contains(_currentSortOrder) ?
                HttpContext.Session.Get<SortStateStorageType>(_currentSortOrder) : SortStateStorageType.No;
        }
        private int GetCurrentPageFromSessionOrSetDefault()
        {
            return HttpContext.Session.Keys.Contains(_currentPage) ?
                HttpContext.Session.Get<int>(_currentPage) : 1;
        }
        private string GetCurrentFilterStorageTypeOrSetDefault()
        {
            return HttpContext.Session.Keys.Contains(_currentFilterStorageType) ?
                HttpContext.Session.GetString(_currentFilterStorageType) : string.Empty;
        }
    }
}

WebApp/Views/StorageTypes/Create.cshtml
@model WebApp.Models.StorageType

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Добавить</h1>

<h4>Тип складского помещения</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Temperature" class="control-label"></label>
                <input asp-for="Temperature" class="form-control" />
                <span asp-validation-for="Temperature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Humidity" class="control-label"></label>
                <input asp-for="Humidity" class="form-control" />
                <span asp-validation-for="Humidity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Requirement" class="control-label"></label>
                <input asp-for="Requirement" class="form-control" />
                <span asp-validation-for="Requirement" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Equipment" class="control-label"></label>
                <input asp-for="Equipment" class="form-control" />
                <span asp-validation-for="Equipment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернутсья к списку</a>
</div>

WebApp/Views/StorageTypes/Delete.cshtml
@model WebApp.Models.StorageType

@{
    ViewData["Title"] = "Добавить";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Удалить</h1>

<h3>Вы уверены, что хотите удалить эту запись?</h3>
<div>
    <h4>Тип склада</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Temperature)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Temperature)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Humidity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Humidity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Requirement)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Requirement)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Equipment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Equipment)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> 
        <a asp-action="Index" class="btn btn-info">Вернуться к списку</a>
    </form>
</div>

WebApp/Views/StorageTypes/Details.cshtml
@model WebApp.Models.StorageType

@{
    ViewData["Title"] = "Подробности";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Подробности</h1>

<div>
    <h4>Тип склада</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Temperature)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Temperature)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Humidity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Humidity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Requirement)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Requirement)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Equipment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Equipment)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-warning">Редактировать</a> 
    <a asp-action="Index" class="btn btn-info">Вернуться к списку</a>
</div>

WebApp/Views/StorageTypes/Edit.cshtml
@model WebApp.Models.StorageType

@{
    ViewData["Title"] = "Редактировать";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Редактировать</h1>

<h4>StorageType</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Temperature" class="control-label"></label>
                <input asp-for="Temperature" class="form-control" />
                <span asp-validation-for="Temperature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Humidity" class="control-label"></label>
                <input asp-for="Humidity" class="form-control" />
                <span asp-validation-for="Humidity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Requirement" class="control-label"></label>
                <input asp-for="Requirement" class="form-control" />
                <span asp-validation-for="Requirement" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Equipment" class="control-label"></label>
                <input asp-for="Equipment" class="form-control" />
                <span asp-validation-for="Equipment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-info">Вернуться к списку</a>
</div>

WebApp/Views/StorageTypes/Index.cshtml
@using WebApp.ViewModels
@model IndexViewModel<StorageType>

@{
    ViewData["Title"] = "Список";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Список типов складов</h1>

<p>
    <a asp-action="Create"
       class="btn btn-outline-success">
        Добавить
    </a>
</p>

@using (Html.BeginForm("Index", "StorageTypes", FormMethod.Post))
{
    <fieldset>
        Тип склада:
        <input type="text" name="searchStorageType" value="@ViewData["searchStorageType"]?.ToString()" />
        <input type="submit" value="Найти" class="btn btn-secondary" />
    </fieldset>
    <br>
    <p>
        <a asp-action="Index"
       asp-route-resetFilter="@true"
       asp-route-page="@Model.PageViewModel.PageNumber"
       asp-route-pageSize="@Model.PageViewModel.PageSize"
       class="btn btn-warning">
            Сброс фильтра
        </a>
    </p>
}

@await Html.PartialAsync("_PageButtons", Model.PageViewModel)

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewBag.Name">
                    @Html.DisplayNameFor(model => model.Items.FirstOrDefault().Name)
                </a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewBag.Temperature">
                    @Html.DisplayNameFor(model => model.Items.FirstOrDefault().Temperature)
                </a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewBag.Humidity">
                    @Html.DisplayNameFor(model => model.Items.FirstOrDefault().Humidity)
                </a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Temperature)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Humidity)
                </td>
                <td>
                    @await Html.PartialAsync("_EditDetailsDelete", item.Id)
                </td>
            </tr>
        }
    </tbody>
</table>

@await Html.PartialAsync("_PageButtons", Model.PageViewModel)