WebApp/Controllers/StoragesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Data;
using WebApp.Infrastructure;
using WebApp.Models;
using WebApp.Models.SortStates;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class StoragesController : Controller
    {

        private readonly RecPointContext _context;
        private int _pageSize = 50;
        private string _currentPage = "pageStorages";
        private string _currentSortOrder = "sortOrderStorages";
        private string _currentFilterStorageType = "searchStorageTypeStorages";
        private string _currentFilterName = "searchNameStorages";

        public StoragesController(RecPointContext context)
        {
            _context = context;
        }

        // GET: Storages
        [ResponseCache(Location = ResponseCacheLocation.Any, Duration = 294)]
        public IActionResult Index(SortStateStorage? sortOrder, string searchStorageType, string searchNameStorages, int? page, bool resetFilter = false)
        {
            IQueryable<Storage> storages = _context.Storages.Include(s => s.StorageType);
            sortOrder ??= GetSortStateFromSessionOrSetDefault();
            page ??= GetCurrentPageFromSessionOrSetDefault();
            if (resetFilter)
            {
                HttpContext.Session.Remove(_currentFilterStorageType);
                HttpContext.Session.Remove(_currentFilterName);
            }
            searchStorageType ??= GetCurrentFilterStorageTypeOrSetDefault();
            searchNameStorages ??= GetCurrentFilterNameOrSetDefault();
            storages = Search(storages, (SortStateStorage)sortOrder, searchStorageType, searchNameStorages);
            var count = storages.Count();
            PageViewModel pageViewModel = new PageViewModel(count, (int)page, _pageSize);
            storages = storages.Skip(((int)pageViewModel.PageNumber - 1) * _pageSize).Take(_pageSize);
            SaveValuesInSession((SortStateStorage)sortOrder, (int)page, searchStorageType, searchNameStorages);
            IndexViewModel<Storage> storagesView = new IndexViewModel<Storage>()
            {
                Items = storages,
                PageViewModel = pageViewModel
            };
            return View(storagesView);
        }

        // GET: Storages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Storages == null)
            {
                return NotFound();
            }

            var storage = await _context.Storages
                .Include(s => s.StorageType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (storage == null)
            {
                return NotFound();
            }

            return View(storage);
        }

        // GET: Storages/Create
        public IActionResult Create()
        {
            ViewData["StorageTypeId"] = new SelectList(_context.StorageTypes, "Id", "Name");
            return View();
        }

        // POST: Storages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StorageTypeId,Name,Number,Square,Capacity,Occupancy,Depreciation,CheckDate")] Storage storage)
        {
            if (ModelState.IsValid)
            {
                _context.Add(storage);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StorageTypeId"] = new SelectList(_context.StorageTypes, "Id", "Name", storage.StorageTypeId);
            return View(storage);
        }

        // GET: Storages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Storages == null)
            {
                return NotFound();
            }

            var storage = await _context.Storages.FindAsync(id);
            if (storage == null)
            {
                return NotFound();
            }
            ViewData["StorageTypeId"] = new SelectList(_context.StorageTypes, "Id", "Name", storage.StorageTypeId);
            return View(storage);
        }

        // POST: Storages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,StorageTypeId,Name,Number,Square,Capacity,Occupancy,Depreciation,CheckDate")] Storage storage)
        {
            if (id != storage.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(storage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StorageExists(storage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StorageTypeId"] = new SelectList(_context.StorageTypes, "Id", "Name", storage.StorageTypeId);
            return View(storage);
        }

        // GET: Storages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Storages == null)
            {
                return NotFound();
            }

            var storage = await _context.Storages
                .Include(s => s.StorageType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (storage == null)
            {
                return NotFound();
            }

            return View(storage);
        }

        // POST: Storages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Storages == null)
            {
                return Problem("Entity set 'RecPointContext.Storages'  is null.");
            }
            var storage = await _context.Storages.FindAsync(id);
            if (storage != null)
            {
                _context.Storages.Remove(storage);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StorageExists(int id)
        {
          return _context.Storages.Any(e => e.Id == id);
        }
        private IQueryable<Storage> Search(IQueryable<Storage> storages,
            SortStateStorage sortOrder, string searchStorageType, string searchNameStorages)
        {
            ViewData["searchNameStorages"] = searchNameStorages;
            ViewData["searchStorageType"] = searchStorageType;
            storages = storages.Where(e => e.Name.Contains(searchNameStorages ?? "")
            & e.StorageType.Name.Contains(searchStorageType ?? ""));

            ViewData["Name"] = sortOrder == SortStateStorage.NameAsc ? SortStateStorage.NameDesc : SortStateStorage.NameAsc;
            ViewData["Capacity"] = sortOrder == SortStateStorage.CapacityAsc ? SortStateStorage.CapacityDesc : SortStateStorage.CapacityAsc;
            ViewData["CheckDate"] = sortOrder == SortStateStorage.CheckDateAsc ? SortStateStorage.CheckDateDesc : SortStateStorage.CheckDateAsc;
            ViewData["Depreciation"] = sortOrder == SortStateStorage.DepreciationAsc ? SortStateStorage.DepreciationDesc : SortStateStorage.DepreciationAsc;
            ViewData["Number"] = sortOrder == SortStateStorage.NumberAsc ? SortStateStorage.NumberDesc : SortStateStorage.NumberAsc;
            ViewData["Square"] = sortOrder == SortStateStorage.SquareAsc ? SortStateStorage.SquareDesc : SortStateStorage.SquareAsc;
            ViewData["Occupancy"] = sortOrder == SortStateStorage.OccupancyAsc ? SortStateStorage.OccupancyDesc : SortStateStorage.OccupancyAsc;
            ViewData["StorageType"] = sortOrder == SortStateStorage.StorageTypeAsc ? SortStateStorage.StorageTypeDesc : SortStateStorage.StorageTypeAsc;

            storages = sortOrder switch
            {
                SortStateStorage.NameAsc => storages.OrderBy(s => s.Name),
                SortStateStorage.NameDesc => storages.OrderByDescending(s => s.Name),
                SortStateStorage.CapacityAsc => storages.OrderBy(s => s.Capacity),
                SortStateStorage.CapacityDesc => storages.OrderByDescending(s => s.Capacity),
                SortStateStorage.CheckDateAsc => storages.OrderBy(s => s.CheckDate),
                SortStateStorage.CheckDateDesc => storages.OrderByDescending(s => s.CheckDate),
                SortStateStorage.DepreciationAsc => storages.OrderBy(s => s.Depreciation),
                SortStateStorage.DepreciationDesc => storages.OrderByDescending(s => s.Depreciation),
                SortStateStorage.NumberAsc => storages.OrderBy(s => s.Number),
                SortStateStorage.NumberDesc => storages.OrderByDescending(s => s.Number),
                SortStateStorage.StorageTypeAsc => storages.OrderBy(s => s.StorageType),
                SortStateStorage.StorageTypeDesc => storages.OrderByDescending(s => s.StorageType),
                SortStateStorage.OccupancyAsc => storages.OrderBy(s => s.Occupancy),
                SortStateStorage.OccupancyDesc => storages.OrderByDescending(s => s.Occupancy),

WebApp/Views/Shared/_EditDetailsDelete.cshtml
@model int

<a asp-action="Edit" asp-route-id="@Model" class="btn btn-outline-warning">Редактировать</a>
<a asp-action="Details" asp-route-id="@Model" class="btn btn-outline-info">Подробности</a>
<a asp-action="Delete" asp-route-id="@Model" class="btn btn-outline-danger">Удалить</a>

WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-darj bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Positions" asp-action="Index">Должности</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Сотрудники</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Storages" asp-action="Index">Склады</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="StorageTypes" asp-action="Index">Типы складов</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="RecyclableTypes" asp-action="Index">Виды вторсырья</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AcceptedRecyclables" asp-action="Index">Принятое вторсырьё</a>
                            </li>
                        </ul>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_LoginPartialReserve.cshtml
@using Microsoft.AspNetCore.Identity
@using WebApp.Models
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <ul class="nav navbar-nav navbar-right">
        <li class="nav-item">
            <a asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity?.Name!</a>
        </li>
        <li class="nav-item">
            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
            </form>
        </li>
    </ul>

}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a asp-area="Identity" asp-page="/Account/Login">Вход</a></li>
        <li><a asp-area="Identity" asp-page="/Account/Register">Регистрация</a></li>
    </ul>
}

WebApp/Views/Shared/_PageButtons.cshtml
@using WebApp.ViewModels

@model PageViewModel

@if (Model.PageNumber > 2)
{
    <a asp-action="Index"
   asp-route-page="@(1)"
   asp-route-pageSize="@Model.PageSize"
   class="btn btn-outline-dark">
        &lt;&lt;
    </a>
}

@if (Model.PageNumber > 1)
{
    <a asp-action="Index"
   asp-route-page="@(Model.PageNumber - 1)"
   asp-route-pageSize="@Model.PageSize"
   class="btn btn-outline-dark">
        @(Model.PageNumber - 1)
    </a>
}

<a class="btn btn-dark">
    @Model.PageNumber
</a>

@if (Model.PageNumber < Model.TotalPages)
{
    <a asp-action="Index"
   asp-route-page="@(Model.PageNumber + 1)"
   asp-route-pageSize="@Model.PageSize"
   class="btn btn-outline-dark">
        @(Model.PageNumber + 1)
    </a>
}

@if (Model.PageNumber < Model.TotalPages - 1)
{
    <a asp-action="Index"
   asp-route-page="@(Model.TotalPages)"
   asp-route-pageSize="@Model.PageSize"
   class="btn btn-outline-dark">
        >>
    </a>
}